### ISSUE TITLE
Add TweetLoader Class

### ISSUE THREAD

**Issue by dieko95** [code-for-venezuela/c4v-py#31]
```
As a user, I want to use a method to query `angostura.tweets` 
by batch size and batch number,
and have as output these tweets as `tf.dataset` type. 
```

## About this Class
This class is an abstraction of `AngosturaConnection`. The method is to be implemented it as a generator. The user just uses it in a for loop.

## Purpose
Perform query paging to return batches of tweets that will be consumed the vocabulary modules.

## Parameters
- Batch Size, Batch Number

## Returns
- tf.dataset.

# Tasks 
- [x] Create `TweetLoader` class. 
- [x] Integrate `AngosturaConnection` within the constructor. 
- [x] Create `load_sinluz_rawtweets` method.
- [x] Logic that converts parameters `batch size` and `batch number` to SQL query.
   - Sort it descending by timestamp of the tweet. 
- [x] Return tweets as a `tf.dataset`.
- [x] Create respective test.

**Comment by dieko95** [comment]
# Tasks 
- [ ] Create `TweetLoader` class. 
- [ ] Integrate `AngosturaConnection` within the constructor. 
- [ ] Create `load_sinluz_rawtweets` method.
- [ ] Logic that converts parameters `batch size` and `batch number` to SQL query.
   - Sort it descending by timestamp of the tweet. 
- [ ] Return tweets as a `tf.dataset`.
- [ ] Create respective test.
