### ISSUE TITLE
Add PSCDD - Negative Labels

### ISSUE THREAD

**Issue by dieko95** [code-for-venezuela/c4v-py#57]
# Problem 

The NGO's tagged data only contains positive labels (e.g., this tweet IS a public service report). At this point, we haven't included negative labels (e.g., this tweet is NOT a public service report).

# Proposed Solution

Add negative labels from the 2020 tagged data.

# Tasks

- [ ] Use the data annotated last year in C4V for Negative Labels (and positive if quick) 
    - [ ] Compare last year's annotated data schema with positive label dataset to assess if it's possible to include it. 
    - [ ] If possible, add the negative labels to the development dataset.

**Comment by dieko95** [comment]
test issue

**Comment by dieko95** [comment]
test issue 2

**Comment by dieko95** [comment]
test comment

**Comment by dieko95** [comment]
comment 2

**Comment by dieko95** [comment]
comment 3

**Comment by dieko95** [comment]
I will pause this issue and advance on #75 . Fetching negative-labelled articles might take at least 1 week.

cc @Edilmo
